apiVersion: apps/v1
kind: Deployment
metadata:
  name: mjyf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mjyf
  template:
    metadata:
      labels:
        app: mjyf
    spec:
      containers:
      - image: okteto.dev/mjyf:latest
        name: mjyf
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0f97e38c-8e5d-4035-a5c1-1ed48dd639da"
        - name: Vless_Path
          value: "/vl563"
        - name: Vmess_UUID
          value: "0f97e38c-8e5d-4035-a5c1-1ed48dd639da"
        - name: Vmess_Path
          value: "/vm680"
        - name: Share_Path
          value: "/v2link"
